ARDUINO_DIR  = /usr/share/arduino

ARDMK_DIR = /usr/share/arduino

PROJECT_DIR = $(HOME)/rcrd_synth/arduino/Rcrd_Synth_IO

USER_LIB_PATH += $(HOME)/rcrd_synth/arduino/Rcrd_Synth_IO/libraries

ARDUINO_LIB_PATH += /usr/share/arduino/libraries

ARDUINO_LIBS = SerLCD LiquidCrystal_I2C Wire SoftwareSerial
#ARDUINO_LIBS = Wire SoftwareSerial 

DEVICE_PATH = /dev/ttyACM0

BOARD_TAG    = mega2560

#ARDUINO_PORT = /dev/ttyACM0

#MONITOR_PORT = /dev/ttyACM0

#MONITOR_BAUDRATE = 9600

ALTERNATE_CORE_PATH = /usr/share/arduino/hardware/arduino

#BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders

include /usr/share/arduino/Arduino.mk
